# Generated by Django 3.2.9 on 2021-12-01 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('online_class', '0004_auto_20211201_0832'),
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('description', models.TextField()),
                ('group_class', models.CharField(choices=[('1A', '1A'), ('2B', '1B'), ('1C', '1C'), ('2A', '2A'), ('2B', '2B')], default='1A', max_length=2)),
            ],
        ),
    ]
